# @param {String} s
# @param {String} t
# @return {String}
def min_window(s, t)
  p Time.now
  dp = (s.length).times.collect{ (t.length).times.collect { false }}
  last_seen = (s.length).times.collect{ (t.length).times.collect { -1 }}
  0.upto(t.length - 1) do |t_idx|
    0.upto(s.length - 1) do |s_idx|
      if t_idx.zero?
        dp[s_idx][t_idx] = s[s_idx] == t[t_idx]
        last_seen[s_idx][t_idx] = s_idx
      else
        dp[s_idx][t_idx] = s[s_idx] == t[t_idx] && dp[last_seen[s_idx - 1][t_idx - 1]][t_idx - 1]
      end 
    end
  end    
  p Time.now
  res, stack = [], []
  0.upto(dp.length - 1) do |row|
    if dp[row][0]
      stack.push(s[row])
      find_words(dp, s, t, row + 1, 1, res, stack)  
      stack.pop
    end
  end
  res.first || ""
  p Time.now
end

def find_words(dp, s, t, row = 0, col = 0, res = [], stack = [])
  if col >= t.length
    while !res.empty? && res.last.length > stack.length
      res.pop
    end
    return res.push(stack.join)
  end
  return res if row >= s.length  
  stack.push(s[row])
  if dp[row][col]
    find_words(dp, s, t, row + 1, col + 1, res, stack)
  else
    find_words(dp, s, t, row + 1, col, res, stack)
  end
  stack.pop
  res  
end


def min_window(s, t)
  dp = 2.times.collect { s.length.times.collect{ -1 } }
  0.upto(t.length - 1) do |t_idx|
    0.upto(s.length - 1) do |s_idx|
      if t_idx.zero?
        if s[s_idx] == t[t_idx]
          dp[t_idx % 2][s_idx] = s_idx
        elsif s_idx > 0
          dp[t_idx % 2][s_idx] = dp[t_idx % 2][s_idx - 1]
        end
      else
        #if s[s_idx] == t[t_idx]
          dp[t_idx % 2][s_idx] = dp[(t_idx - 1) % 2][s_idx]
        #end
      end
    end
  end
  dp[(t.length - 1) % 2]
end


p min_window "abcdebdde", "bde"
exit
p min_window "cnktshvvjnnwftckuerryorwnpirtxjgvzxyfxmnwtcrwdycwdndcguzzvziachknezyxsefcxdjnmncuzgeosxrswnkfsoioezgwwnhkfpruwvleohnhgdcrhljvuxovajjpznmemjefmzxcfycskqwiqybpjzqdnqgvqaaxfhobugozbccxlvzwyedqcdilzrqaxqalggwjoyzexdtxadjbtryuxzhplvihxewahnldiuvvfajnmtiwbrkumvepnwvufxhbwkravnbwhjtgigngxohbtuakxhftttyluatnasevhpxcgiqertakkldcojqyvqwtbowliufswqfzmtcgoaejgnwtwobrskkzbmsspcpveqrhfertkeitdomceozpdrfeemfgggzwfywvlovkpsxwhmgfhlqjlkmpraerxlnmkhjciziivtrvbduapionqlmgbgbrmpavvsfvmbgtczxitctsuqskkmfcsrmvbgoygkawcxxccpzefzddtajwnlwjvfvhegwyforoymslmynhexdvftlhvstybaboduqcjwcrbmtonvdfvjthyaukrddvvypdxbavtavdzlzejyayevkneupnafnvmdekmloeowmrppvlzpdtoszxqbsbugmjjcorsvmbcydzmzegoypqkfsjutadgdthbfgxnrnqacmagdmmhqcoxdvsocmwdopvyfsthczdyzxnrpdysagsuvecbpodjsvgfyohcotnabrnbbtgfmvlkxfietcpwiwlwloxskwfesezaozkdmwqmccqstctvrmijxsndduiqphtkbqnhmimfmfigkwanhglnvegxpswsplscnumykeyeeguvybhjqsalaajpxuucglrsxuccuussnlgmovkwpclajxwqpekpsklhhnmcdpdtrtmlyxhwzebvesjjgirfpvwyscwgkesahngjahacftxxoyevubhxlcsrpyxjwyyzdgsavkfkmoxrhjzvnquutgncyedgcmkhlomkdjjhnhbiefgnnyiqbhzkwfefgnzdyuhnecwgeqimempikgswvhnfewstpuvxwewgdlmeeicqqifmsxjjclwjsjctkeveuqfryqyuvahtxybgdufvdtaefnvnrooiofmesjypuegncrtvqhxussokaraopboqnngqebuueolxulrmwfdihjplfmiottohagheohyhsndmaldbupcqiflsklhhhubmpybgzggmsjhrhydjzgbyeljdzxlkzzdjqfngetkvkystbcetaxmycdsygtwvjvieehtetvtelxhldbcjnuawdoepicnitdymznrykpmpiexquobsaqylguwbdnulupzuchkxfpxrtjmecuckcigucggzieergyxhfmuiaaudnebsjpcrekmibkxylejpcmcmyivavsnbzoairaiafvikymdndjbqzkbdpzbenzhtnloqqkwtsvchejngxravpfwmcppdkoxsxcxwwursdcpqxrcbbtkammzpalutgkhlfegafzfusbtfzfdlpeyljiaqqddwtopkjmpllfacqwckirhwiqudfomcbhhroftcgrlekzmxxhhhinqwayyjbanmekzagyghkhzkmokhoojotfnznamekmhqptnkkqzcalhuiqsnpedcmowfjkyfhqjpsuowwrpdgxqcvyeuvijckhkoxeslqzexovcliqkkewdlzxveurjycsjrpubfxjcutvmniqnzdakwbdrwxxnmpzityozccozzmrunjgzryylaqpfuqxaqmrzpwjcfgscupkavzrocuizmmmffgzselluxhrgzizokacdsoaovdbeovbezzvrdsscofwkbiasytokpylwxmroekjyodhlulubkkjuxtcatmcjknpjeeuuysrmtfjvduqyifvpcjkcqoobdpdtcvsgtkjfghaelzpqytixemppcqrkfhwdilbkurywafiwbqeywcqyniypdxgcyfhkmmnnycaonwgsqwwswkkjkkofyjxiihaeswxjlglcmzghxdjvkhadjxatyqcsvtmvyrbjadlnvwsrmadgqnmkxmkoqfiydubdzxspyygmjiaorkfcxlsktcqtwojngoxfzjjdnupbfvagukavprsseanygyhywtixtxqochiiizchyusfwzktfwgcuvfjgcwqvwgsdwkodtpphxxddtdzionwqttvrsocpkhpgljvhdzgfmfgirszfpignwnkrxuccmqcljpdlgaxnfiaeeadrkqxegfedbpnjnpyobactbjoqfppkhiicohesrhjunplsmipuhxfsaumeqcrukxhfoacvobqavodstisklsxjwqtfbhycmleycdomvakdkbduzwksmgfjcdansworblcpvnzzfgzpmelictpyuqchonlduzfltlbskpfqrisshtaambszqqergfeefkvkiogrgwknepimwoqoxbdjdyisxeocdjocqqqcxemiuzzburlxzogsjcylrpgsmqgwzyynvxjxglfyerlfmzogaznhkkspcsomvvixpukzifbflzkcdfmeaxvwuhxszzmdxujtgqpphnmsuhjzszvsnvsykuokzwauiytajvohmmmwbyikmzwpcyodaxdonkeczgcmedfkoafpnclvhspddcpycrtlvqihxvtefrwmmkbpujccauhdsnlidiekgnxgwiwbimrdbwxqdosqoczluwzpaiunibzrewyopculgbhzjxqzdqgrfkrhslxvdvxypxaxjphqcoujfkalcfjopujlgowbsoctvqxdlkoceyngwtauwxcivwezgorjnkwacuyvyhlndztnxkqwflmqyoxnhtbzfzsoglazflewfqzixlvzmmrmihuexgehifhsbrvqeafdmjixgrzqsxppnvlcrmzxoufkfihwxkpimwwcdlldvdifigzfqhknxqmbaqdriyoztlniywvgjvcoaprfgwlwvwmddsxtlzvxhhmqhktlpmfdtiqnzbpqaclxtddwhpqdnkswoldhgcldcuaxvtieygsjmjgokfmmyfxvzryvluovavzhobgwrmkceqayvkwsvxtksqqxgfgadazgfmhgdsxjqakcuapfqggoumfoqugazlvnupwneheathmofbsqqilrbyvcnejjvknktenkmwvzocyrxwifjhrtkkvvyhloqnjyqmiaarrunwpxlttzvgvbicbktedyxdzwdooghxapvydbxiwmgvykfoylyxvxajpjemwvgygdeddwlzzdvyfnhqezhyqrsxcgvrrgworoynclzyjqpqovlpnjvqcluhjuoubsowraehpjmlpdnxeeanoikvynzejzijyupwxclupdpvbeqjkamfppjbirtztttajigqpqcqzprpwnclczpqoqvtpejibqdurjmhlvfongstxjyinkpbvlxplufjefpirxivjusjbexhulhvzhmsvorlnsulffysovkljqsdkrgpakozcdoneswhgwmdkzfwanjegxzcxlsnwzqvwqdoezufibpmgeuilgnakundeskyiddhskgdkryhnjxcmujlytukhypquofveiwqwaylrlgqyhmyrnckvdlekbguphwuajchmqwialethmfpkswaqfbdxporwqjluaemxabukwamajjrcoapuzpnnbleapcaqonxnbhfbbdoffbhuimrawgdusrkvpbpbmrwmsprxfqjerovruewjixyfdxfsyseolnztyusbtzfnlcfygpwwogystbtrddqcrhoiqvmrdzglohzhsmwlvfqwtrdvspfvofxaynenoaivxxcpuzeswdzqjxknwdrrlronqkfaepmqltdeiizhkxkqeohexggdrfegsiwjzipextyrybgttgghfbgfhjnvzwkpipguuevqwwjyyjculvkxjeiwhuowbeofmsysbsemjlrnejuonsofjlueexsgsupmrepknjtvrgbczzdvphfnsavcikhdlrycasxhfjaktukleqkaqybljrypkajbrhofpqsqtzuphixogloroidliepvzwnufaacsrzedslnbnauermotqhmstthfavourpvxrtwejmhdtlyhghtcdtkjemumbijzwbuervgqnhdmmknfkgcefnnjajsrqnwqjligdgwshgudwtswrdnfzrvqpvcjanvfbkaoykyzvjugwcdmyxzjxoynuuewvjqrvapfcbulcaplshpgvjithcvvklszenadnkejwkwzmzuyqmedjhgaongcowisexptzhpxbbqkslbccgufgkivrvgnbrqbeznbbxuybpvsbsicppjankfeiporftbmuhrsrrpfnqnresowwhffzffgguvkeddbozcphysxxdefilnmttunvllswisylirrlhszrbkcxefsvchwotxiwhbpzhydkmggcqjuwftskjyluvptnxegkzauezmvmtstzhphddittnsbrpsnedfhkaeapxwfyylthmguzrwezispcqnsoqyxjflkerbepjuisfriqqccvzjgaddrushpywnhirkbrcdvlhnasatsptfhrwymunnkhljvnopauzsxwxgywrzpndnvbizxzrblgngiztotethumpgkyrgtsqpzhvsbrjwbmmfzrdwlromamktqwjmikultfcpxjhilhcfzvqzkqpsjmqlmkcmpeuihxcgairnzcxctxvpljdptusylasvgzovqlpnpgqzvwszcxfgbdexyjafozrgssyqgzqpesprxdfzwtzgzbygohfpwrnpsbixqoqazakwkfphooqjdwgbgznqcgseshaijaymuiibybkfgtefiudqsnmkakykisyghdkqlsbzvjvygkoqfjojttetujtwmjweajqanfxkrgatclvsiqgdvxhabgaosnppauctcyokyiduvolewrrejwcfwwfpsrojylqqmghgyqvfvhffyxmcxrukmdgkbjtvyuddlidchdxfypteagwbwpurzhuaunainneqzvrbesvnynvfdcqvkrlkoedzcckkhdujfosntmnywzriwzaabkwhrifaofxzzxusscxzmyilpopaxrrrhctlhsecabzyasbaiqhwbhmmejvvutshybsfaqlxcvefangxbquzdlioobhfocjpitdvbzhtpgtdbhdgnpgfrfpafawwwziysbdbmzkwvulqbljqlaanshfblfgmrghropzawtxeprrqaoyegljjyekfapaqhpeoymjdpagxszetwaewbcycwmxmcriayniyzlwsnziifaysianuoygbqhubeqfjymafzeoxmawxtdxxbaobmfqdvdpkjgzhtdclfbrfwdrzstyhbukqjenudyqjgsgthgzpipizpaowcfiiafwflgltxzpijoytocluvqlmufbqxndgrtvkaktxlzllefzhnizdesmbmqzjsefwofwajcdawkqegghrhkxnzvfpskthktbyzzcbotfdvvbwdpiuskxuqujakrmnxafgrahwcfpoesbtlnuzoktzvezsxkwnxxnqlstaagjpobbdzzdzlfktgwdddemucejffgqpbisvdexpcegijmwrbtxhrimincyamurnfnhpoaupiokjhrgsrtbdlmmwypsvpzdyltkzbaknxcwbabnebrwpfaldigxptxneyiolkinegfkebeakontlolhytbdobtzguyjvzahultyysxuilxffoowovcnncwfvqvxvxjjkadsrgdivzeyfvbtygjehfirilrivkgqkagayotmyjniwhxpmvfnvkazfophffofalopxdvfuyozfzbswynuqhcnnnjnuonrojcrjbdpebvgueyvmcrmmmkrmiiyumpavhyiktejbucgolihtltpogtgcvrryuttigbcegnssfvrnnudyuheyserppzvzncfgurdzhezbadbpnniclevsszmhjnkvqrtuvuhawjsdjluodcwzvcitfcydtaxljjzttuwyufgumtvfohsqwhqlucrnlmkdnvrjmuufscnopcbaadtunhpmfhrezvbzgrgavpgzecdrampabbzwzutfjaxekccifvwbzposkmowhrggdbplpwxqdkanxltrxwakafvsmkldmistnlbtiphwhqbrkgrehxmkuartsnjklndncrobiefwxkerbyddpcymrjpbbikvtjgjnpdviljxywncccbyajkvhtnvybaetrqggdhvuhjqwwmnogvyctofzvavdnhwyrooevdwxiehztywcpaktimvvimrwqiiuiahjedvhcfmqvseugksfwququwvsjewjjxxehmgnnmunfhuvvtnlpeicojfqlxiqccqplzpbspruapavyxehvvhhtldjdvldgqwhxugrzhpibpyvhdkqkqorworgwdnzjqnfjcjqeciezzlvhygzwwllkuvsmahxfxvysqmjeltlqriibyqqsxojypvaeeobpzmuptccqcprpomxmtzjgrmnsnhqwwxhfxfcdqskjleisfgoqjoedmisahrdlgkmmbvrgljepgunaqctazghpmacembrbiepypyevwpfsodklhtpuohpwdiulbsbrsajzxdbevswppaulfewmshvvjmkffvmhtdimfjymjsuycjrwcgzbnsdmftvzraelvhjjqbbzduyzygqnfdfoyhzfltogrihfjnjpilwmdscecjolzkkhxjzxnvpjeamzknfinzzwniwqxqicqpxndlrprudfylbdxrqxqrgttyeijosqwewcuiwszzthhvcakhqhdauftuhjlrnkplynewxokycgttfkhhjorgxurnqgkxgzsinawnxszeifbpkrgbccnhnrrgzemtrbgzqduxpihcspgxjxppstwxzpymvnzowceagwdkvdwuhclqdpvufolmuhsmhwyvjxgpbxhiiayyatnujbcxmutxigryedxbwzpsjlwuvwxyiramufhutzhiblaosvskxgnhusjdhgkhcgahzutilyddnhqgpjvfjbvmselkbnfkhmodcrexrxbhgehbdustdnlgyicgdvcncmatiwcindbhhhutuayeoaqyhohztiftlhzkwjqdfiwxiltbhwjrrywcyeqgyhexeabwthtazeqzxzfjpfxgxnfyblmfgydtlitudiehnjhqbarsmijrcxkinycdkxmrsupwitonxvsirbhzuynolbbuzsfpgxnzsndmxjvqkvllcufrdkzjdgrdoyqqjxsgxsulfbbpwhggeerbsrrlzhtecjkrvllfwhzgrnhmtwvfiyzcuwcerbiuuidrgbaudrfklwhaalnvguiheitidwgjrbntdoyeuawzegcobnbetzjlzczgstoakfwwulruryadzsaoqqacmtbgrirledcnqicsmirincktndneimctlkaddlbflsrhiunnpoercwsburefswuhmrqigzaibdzyxnxvncyonlfvwhnyxwfjmordshdcqgysbqpqezevtigexnrihwygbuokniycnfloaltnkslhoakqrdkrxsdfcleyfftoitmpprkwsctkyxfphqlrbramofjzaxoiylmttaaoizgoqkxtpervzaevsulmfhnjlttctxfluwhriwcvrdkktfxsplojdrfpwxxvslxkcjoerowlcdvaozxexumcxovvbkozaeibkqlvpdhdruscqjzecyuevjvntmasjuxivkirytoynzghicbwckthidofsethngqnujwznvulhqycbuptzhydqqpbuygazggzznxjebfbuhsqzbjbhcfizzflptlagdbywrkjnfbsfjivfptvxdvcwehmkvmqiiqwsjvsdjitfixcabixbmvuxdmnjfdkqrqeymvwpdjvtlworalfxdtspmiihqdbhsuywnpkbxipdpjgrageuxfzrnksjfuogoelguesqhzoxuxmtlylknsgeazkkmzxguanriktzajslmaihdnpxauhijbufkgbyxnovexglzpzdyxmjjxrmbofyhnwbsmcrodkfamdvwzxnjamizveiaopjswwgvtnsgkbjjlpgvsuzgclajsxypscbrzdrkkcanziqggmncalhiqjakhlkfydplkojqiletisbctfzcphibuctjavyuqqrmcbfjbtenzqckmonfpgqtujahwjyulwxymaflvlkcaihphxltizzeictzjjursggitwedoniejfltmuttsgbyxfniysjkenvuasmoelrhumytjlhvgckgquhzwadoqvxajhjaqwurpprsjgqxhyrxnamifichrjirtzbxwnadvqqzoviryzvseqppehtlbumdmfcpdmcszhxjvluevhvjmsqwczrbfwcabhrsgjbquxufbyxjhbjzzpmsvpwskwhbqudjvcaxqikgynalewmlvbzugsfbwaiwkbpvszkgdjvakzzlsglevvscbmpkfsqemtqjrilkjrqxkjvsnrjcfiigyymgiosobwfkqkmayrrslfjuomhjjkvxpeuesctafwrrhfnupzxhlnzkuqghswcmpehttqngiqndfnwbifdzayvvfombqoozuhmbpqpvkbkdlmmqrmtdxhggysjrcsmlgplakaofzpmbcqiebdaspocflrrslsihrfpsvmloqnqlxbiisfdpmazoscutrjnwmjlsdjzzhidtyscwjfflxtttnyhnxbdjxetlpyvxpzlphxnpesmshypxuxhsfifzkrlzvmblucrdxkpgtnesqxiqrbrgdpezjzzgkrvklgybtyllgtzwqnqpdzqtdcljyjrpbcapqpnkfkqplqpovmksouksntnpohikxlruuoqtoykdsjsadhvnbtchatstrverslajctxshlfqywvivsndbjiswjafwmbesdnazzsackrixiivlxzksbiljhjgbhzqhxxeyxvyjqhmyskqxoezpmclxvuewdjicsqbhpjsslhtsexjxpzfieskjpweilnmcfoxxmnortmjqgbiiuaqvzxcijvxloibamkwvumhkblbqxcgajlkjchtxywpfdwgxqumyawafepcjbaduiiodzjitrqquqfwhnibzgitnlchftaatojaqaqknciaddyanvouqigxqrrsiskljdheqtimwzmdbweccdkibyzhayshykyrfbnbiylpeozcjhostzxcdgmwcfhrfxlcvomkuztsoeanzwrrwpilttxlemxcxgrgibglvwybjuualvnlnpmhpydfmnbhpgnpisuxpykznsexcfctncsiwdokdndartxguvfgxzaepdrzkwgzxglxpaccblvfobtnhbzfyuwofyvuhudwcjcxtgeguztutsnentivkbbovrogoqtxlhcqsaljhzddbtsjleizzuqsgkhhzlvbyhssaxhvlurxbtzbquzuzrqysvgoknchhzfwkvetulawwbzqjkenkufoyviahmoubajzopkewonxenmzpjrzunfislubrvwwhmjrkmuuqafkbzbhwobsnevqeoglgpatmvrpnzqdyabxmfjiyimqitpxnejdgwbgmdktrxnmtlvzasbrjwlealyvsntxhqounrbfdzkamcbygtpttgrnrjdtozapwarmxrvpmmqfeixdgyscieurckdagvolfjrzcjquwlzqhchzyykjwrqjtbngbjlacpbkevqobcieqmuovjgqbomotarpvikdchonhvqltnjgwiqifwxvkdmmmgaozzokxbtzmaadbuvmdpeaphvoqebijsqebbcbzltkjzvthhukobdtxoggyjmzwneeiibsjvzsnevcdevdfxinjanwq",
"ereswethisxakuwzddblzcgpmkbzwnzdiayqlollxctiseifmnpdhacvotczgajpcklgsnylkseejouzhafykbwlnpppwmocybfg"